### ISSUE TITLE
No string wrapping in `withPreviewWindow`

### ISSUE THREAD

**Issue by yankeexe** [ktr0731/go-fuzzyfinder#102]
## Describe the bug
String gets trimmed instead of being wrapped on `withPreviewWindow`

## To reproduce

return a long string from `withPreviewWindow`.

## Expected behavior
String being wrapped and shown in new line.
## Screenshots

![image](https://user-images.githubusercontent.com/13623913/126058831-2d414579-8992-486a-bb1a-3d684a282025.png)

## Environment
- OS: Linux
- Terminal: Alacritty 0.8.0
- go-fuzzyfinder version: v0.4.0

**Comment by ktr0731** [comment]
Hi.
This behavior is not a bug, it's intended.
In some situations, text wrapping behavior may not be desirable. So, go-fuzzyfinder delegates the formatting of the text in the preview window to the user.
Since [`WithPreviewWindow`](https://pkg.go.dev/github.com/ktr0731/go-fuzzyfinder#WithPreviewWindow) option takes width and height as arguments, we can use this as the basis for wrapping the text.
