### ISSUE TITLE
Running the example test breaks the terminal session

### ISSUE THREAD

**Issue by rolandjitsu** [ktr0731/go-fuzzyfinder#106]
## Describe the bug
I was trying to setup a test for some of the code that uses this pkg and it seems like running the simulated term screen breaks the terminal session it's running in. It also doesn't seem to respond to the actual events/inputs (e.g the ESC key) as I have to press enter for the test to actually finish.

## To reproduce

Just run the example test that's provided with this pkg.

## Expected behavior
The simulated term screen should break the terminal session.

## Screenshots

![term](https://user-images.githubusercontent.com/1479737/127794970-9585d34c-fbd4-4328-b5b3-9d384f8b913a.gif)

## Environment
- OS: macOS 11.4, M1
- Terminal: zsh (also happens in bash)
- go-fuzzyfinder version: v0.4.0

**Comment by ktr0731** [comment]
@rolandjitsu 
I'm sorry for the late reply.

Yes, the example test doesn't finish automatically. It is the expected behavior.
There are no ways to succeed in the test without interactive action such that entering keys. Although we can inject something to avoid interactive action, it is not an actual example, just a test for passing the example testing.
So we only check examples' compile error and doesn't test the examples.
I'm sorry to confuse you...
