### ISSUE TITLE
Interaction between fuzzyfinder and subsequent STDIN usage

### ISSUE THREAD

**Issue by akerl-unpriv** [ktr0731/go-fuzzyfinder#17]
## To reproduce

1. Use this go code: https://gist.github.com/akerl-unpriv/d94d02cb21a333776d4ebaf2a24f8849
2. `go run main.go`
3. When prompted to make a select, make any selection from the fuzzy menu
4. When prompted to enter text, type any text
5. Hit enter.
6. Type some more text.
7. Hit enter again.

## Expected behavior

You should never be able to make it to step 6/7; when you enter text at the prompt and hit enter, that text should be captured by ReadString. Instead, something seems to be interacting between Fuzzyfinder and STDIN, that causes the first text and newline to be swallowed.

## Environment
- OS: MacOS (tested on Catalina and Mojave)
- Terminal: iTerm and native OSX Terminal, bash and zsh
- go-fuzzyfinder version: v0.2.0

**Comment by akerl-unpriv** [comment]
It seems like this may be linked to https://github.com/gdamore/tcell/issues/194

**Comment by ktr0731** [comment]
Thank you for reporting the issue.
Just you said, it is caused by gdamore/tcell's bug reported at https://github.com/gdamore/tcell/issues/194 because the issue doesn't happen when using nsf/termbox-go.
One way to avoid the issue is to reverting #8 temporarily. We don't add any features depend on gdamore/tcell, so I think we can replace it without any side-effects.

**Comment by ktr0731** [comment]
gdamore/tcell implementation has been reverted at v0.2.1.
